import re
from typing import Dict, Any, List, Optional

DIRECTIVE_KEYWORDS = [
    r'trả\s+lời\s+(?:các\s+)?câu\s+hỏi\s+(?:từ|sau|dưới|cho|\d+)',
    r'trả\s+lời\s+câu\s+hỏi\s+(?:từ|sau|dưới|cho|\d+)',
    r'hãy\s+trả\s+lời\s+(?:các\s+)?câu\s+hỏi',
    r'câu\s+hỏi\s+(?:từ\s+)?\d+\s*(?:đến|–|-)\s*(?:câu\s+)?\d+',
    r'từ\s+câu\s+\d+\s*(?:đến|–|-)\s*(?:câu\s+)?\d+',
    r'thực\s+hiện\s+các\s+nhiệm\s+vụ\s+sau',
    r'read\s+the\s+(?:following\s+)?(?:passage|text|article|announcement|leaflet|news|advertisement|dialogue|sentences|email|letter|information|piece)',
    r'mark\s+the\s+letter\s+[A-Z,\s/]+(?:or\s+[A-Z\s]+)?\s*on\s+your\s+answer\s+sheet',
    r'refer\s+to\s+the\s+following',
    r'questions?\s+\d+[\s–-]+\d+\s+refer\s+to',
    r'choose\s+(?:the\s+)?(?:best\s+)?option\s+to\s+fill\s+in',
    r'blanks?\s+from\s+\d+\s+to\s+\d+',
    r'numbered\s+blanks?\s+from',
]
DIR_REGEX = re.compile(rf'(?:{"|".join(DIRECTIVE_KEYWORDS)})', re.IGNORECASE)

HEADING_DIR_REGEX = re.compile(
    r'^(?:#+\s*|\*{1,2}\s*)?(?:Cho|Đọc|Sử\s+dụng|Dựa\s+vào|Dựa\s+trên|Theo|Quan\s+sát|Căn\s+cứ\s+vào)\s+'
    r'(?:các\s+|những\s+)?(?:đoạn\s+)?(?:tư\s+liệu|thông\s+tin|ngữ\s+liệu|văn\s+bản|đoạn\s+văn|đoạn\s+trích|bài\s+đọc|bài\s+viết|bản\s+đồ|lược\s+đồ|bảng\s+số\s+liệu|bảng|biểu\s+đồ|hình\s+ảnh|hình\s+vẽ|sơ\s+đồ|bối\s+cảnh|dữ\s+liệu|dữ\s+kiện)'
    r'[^\n]*?(?:trả\s+lời|câu\s+hỏi|nhiệm\s+vụ|sau\s+đây|dưới\s+đây|\d+\s*[-–]\s*\d+|\d+\s*đến\s*\d+)',
    re.IGNORECASE
)

def clean_text(text: str) -> str:
    """Cleans up leading/trailing whitespaces and newlines from extracted text."""
    if not text:
        return ""
    return text.strip()

def clean_tag_text(t: str) -> str:
    """Strips markdown header hashes, bold/italic asterisks, and whitespace."""
    clean = re.sub(r'^[#\*\s\-_>\div<>/]+', '', t).strip()
    clean = re.sub(r'[\*\s\-_:]+$', '', clean).strip()
    return clean

def is_direction_line(line: str) -> bool:
    clean = clean_tag_text(line)
    if not clean or len(clean) < 8:
        return False
    if DIR_REGEX.search(clean) or HEADING_DIR_REGEX.search(line):
        return True
    return False

def clean_stimulus_text(stim: str) -> str:
    """Strips any accidental leading or embedded exam direction lines from a stimulus passage."""
    if not stim:
        return stim
    lines = stim.strip().split('\n')
    rest_lines = []
    for l in lines:
        if not is_direction_line(l):
            rest_lines.append(l)
    return "\n".join(rest_lines).strip()

def clean_stem_text(stem: str) -> str:
    """Strips any accidental generic exam direction lines from a question stem."""
    if not stem:
        return stem
    lines = stem.strip().split('\n')
    non_empty = [i for i, l in enumerate(lines) if l.strip()]
    if len(non_empty) >= 2:
        first_line = lines[non_empty[0]].strip()
        if is_direction_line(first_line):
            first_body_idx = non_empty[1]
            return "\n".join(lines[first_body_idx:]).strip()
    return stem.strip()

def check_and_clean_options(options: List[str]) -> List[str]:
    """
    Checks if all elements in the options list are prefixed with matching alphabetical labels (e.g. A., B., C., D.),
    and if so, strips the prefix and returns the cleaned options.
    """
    if not isinstance(options, list) or len(options) < 2:
        return options
        
    cleaned = []
    matches_all = True
    
    for i, opt in enumerate(options):
        if not isinstance(opt, str):
            matches_all = False
            break
        # Expected letters for index i: 'A'/'a' for 0, 'B'/'b' for 1, etc.
        upper_char = chr(65 + i)
        lower_char = chr(97 + i)
        
        # Regex to match prefix: letter, followed by divider (. or ) or : or - or space), followed by optional space
        pattern = rf"^\s*([{upper_char}{lower_char}])\s*([\.\)\:\-\s])\s*(.*)"
        match = re.match(pattern, opt, re.DOTALL)
        
        if match:
            cleaned.append(match.group(3))
        else:
            matches_all = False
            break
            
    if matches_all:
        return cleaned
    return options

def parse_question_xml(xml_content: str) -> Optional[Dict[str, Any]]:
    """
    Parses XML content generated by the AI.
    Handles both standard and group questions.
    Returns a dictionary representing the structured data, or None if parsing fails.
    """
    # 1. Try to find a group question first
    group_match = re.search(r"<group_question\s*>(.*?)</group_question\s*>", xml_content, re.DOTALL | re.IGNORECASE)
    if group_match:
        group_content = group_match.group(1)
        
        # Extract stimulus (or legacy context)
        stimulus_match = re.search(r"<(?:stimulus|context)\s*>(.*?)</(?:stimulus|context)\s*>", group_content, re.DOTALL | re.IGNORECASE)
        stimulus = clean_text(stimulus_match.group(1)) if stimulus_match else ""
        stimulus = clean_stimulus_text(stimulus)
        
        # Extract all sub-questions
        question_matches = re.findall(r"<question\s*>(.*?)</question\s*>", group_content, re.DOTALL | re.IGNORECASE)
        questions = []
        for q_content in question_matches:
            stem_match = re.search(r"<stem\s*>(.*?)</stem\s*>", q_content, re.DOTALL | re.IGNORECASE)
            stem = clean_text(stem_match.group(1)) if stem_match else ""
            stem = clean_stem_text(stem)
            
            option_matches = re.findall(r"<option\s*>(.*?)</option\s*>", q_content, re.DOTALL | re.IGNORECASE)
            options = [clean_text(opt) for opt in option_matches]
            options = check_and_clean_options(options)
            
            answer_match = re.search(r"<answer\s*>(.*?)</answer\s*>", q_content, re.DOTALL | re.IGNORECASE)
            answer = clean_text(answer_match.group(1)) if answer_match else ""
            
            explanation_match = re.search(r"<explanation\s*>(.*?)</explanation\s*>", q_content, re.DOTALL | re.IGNORECASE)
            explanation = clean_text(explanation_match.group(1)) if explanation_match else ""
            
            questions.append({
                "stem": stem,
                "options": options,
                "answer": answer,
                "explanation": explanation
            })
            
        if not questions:
            return None
            
        return {
            "is_group": True,
            "stimulus": stimulus,
            "context": stimulus,
            "questions": questions
        }

    # 2. Otherwise, look for a single question
    question_match = re.search(r"<question\s*>(.*?)</question\s*>", xml_content, re.DOTALL | re.IGNORECASE)
    if question_match:
        q_content = question_match.group(1)
        
        stem_match = re.search(r"<stem\s*>(.*?)</stem\s*>", q_content, re.DOTALL | re.IGNORECASE)
        stem = clean_text(stem_match.group(1)) if stem_match else ""
        stem = clean_stem_text(stem)
        
        option_matches = re.findall(r"<option\s*>(.*?)</option\s*>", q_content, re.DOTALL | re.IGNORECASE)
        options = [clean_text(opt) for opt in option_matches]
        options = check_and_clean_options(options)
        
        answer_match = re.search(r"<answer\s*>(.*?)</answer\s*>", q_content, re.DOTALL | re.IGNORECASE)
        answer = clean_text(answer_match.group(1)) if answer_match else ""
        
        explanation_match = re.search(r"<explanation\s*>(.*?)</explanation\s*>", q_content, re.DOTALL | re.IGNORECASE)
        explanation = clean_text(explanation_match.group(1)) if explanation_match else ""
        
        return {
            "is_group": False,
            "stem": stem,
            "options": options,
            "answer": answer,
            "explanation": explanation
        }
        
    return None
